### ISSUE TITLE
Google Cardboard Support Please 

### ISSUE THREAD

**Issue by hashchech** [mupen64plus-ae/mupen64plus-ae#411]
The ppsspp emu has it and would be a perfect use with gearvr or Google card board vr

**Comment by kg6zvp** [comment]
This would be an incredible feature

**Comment by RenaKunisaki** [comment]
This would be an amazing feature to have. The basics are pretty simple: divide the screen in half, display different images on each side, let the goggles do the work.

There are a few ways it could be implemented in an emulator:

- Just mirror the screen (same image on both sides); no 3D, but you can play with goggles on (no need to hold your phone and a controller)
- Alternate sides every frame (especially if it's possible to double the game's framerate)
- Do something like Dolphin's free-look feature (might require patching the RSP emulator) to render each frame from two different angles (or, again, alternate angles each frame) for true 3D

Even without 3D this would be a great feature for any emulator, as it'd let you play with a controller in your hand and the phone on your head while leaning back in a chair without having to rig some awkward way to hold the phone.

**Comment by min050820** [comment]
There is a [blog post](https://dolphin-emu.org/blog/2015/05/13/a-second-perspective/) about dolphin's stereoscopic 3d implementation. It's dolphin's official blog, by the way.

To summarize, dolphin used technique @RenaKunisaki suggested **in the past**. But it suffered from disorientation and framerate being half. So, they looked at NVIDIA 3D Vision, and applied that technique to their emulator. It renders the frame ordinary, and uses geometry shader to duplicate objects with respect to perspective. Then it uses separate EFB layers, and it's rendered. (geometry shader is used instead of doubling drawing calls)

Here's the [link to specification of NVIDIA 3D Vision's algorithm](http://developer.download.nvidia.com/whitepapers/2010/NVIDIA%203D%20Vision%20Automatic.pdf). (The link is from the blog post above)

**Comment by fzurita** [comment]
Interesting method of doing real 3d. It seems perfectly doable, it's just finding the time.

**Comment by min050820** [comment]
By the way, when you make it, please make sure to include 'invert option' (swap left eye and right eye). It allows people to experience 3D without any special device.
I'm really looking forward to it. As far as I know, if you implement it in GlideN64, it'll be the first plugin to support stereoscopic 3D for N64! I hope metarials I found is useful :D

**Comment by fzurita** [comment]
This will not happen since google decided to drop all support for this.
