### ISSUE TITLE
Remove "press-and-hold to auto-hold", replace with Turbo

### ISSUE THREAD

**Issue by BonzaiThePenguin** [mupen64plus-ae/mupen64plus-ae#417]
I'm pretty sure the press-and-hold version of the auto-hold doesn't work anyway, and it seems like it'd make more sense to use press-and-hold for an optional turbo for each button. Most obvious place for that option would be under the Auto-hold checkbox in the button editor, although I've never used the physical-controller editor so not sure exactly where it'd go for that.

We could then remove the option in the Global Settings for choosing the auto-hold type, and have it always use "slide off". Never understood why there's an option to disable auto-hold globally anyway – seems like that'd be a controller profile instead.

**Comment by littleguy77** [comment]
The auto-hold feature only pertains to the touchscreen/touchpad form of control.  It doesn't apply to peripheral controllers.

I don't have any issues with the press and hold feature... do you have a specific example where it doesn't work?

To my knowledge no one has ever requested a turbo button feature, so it wouldn't be my highest priority, but I suppose it could be added.

Regarding *removing* an existing feature, that should be discussed on the forum because that is the appropriate venue for discussing userland design/philosophy.

Many questions regarding "why is setting x here" can be answered, "because we are still transitioning from version 2.x to 3.x".  For a brief recent history of the project, I started the drive towards version 3 in fall 2013, but the project went on hiatus and stalled for most of 2014.  When my attention returned in late 2014 I tried to pick up where I left off but in the process committed some buggy stuff related to the touchscreen (as you noticed :) ).

For your specific question, auto-hold in the global settings made complete sense in 2.x since the whole settings profiles concept did not exist then.  Maybe it would be better to remove it from global settings and wrap it into the controller profiles for version 3.  From there, it might be a short hop to adding the turbo feature.  For example, in the touchscreen button position popup, instead of having one checkbox for autoholdable, we could instead have two dropdowns:
 - `On long-press:` (dropdown containing `Nothing`, `Auto-hold`, `Turbo`)
 - `On slide-off:` (dropdown containing `Nothing`, `Auto-hold`, `Turbo`)
So a user could mix and match however they please.

On a related note, I was thinking we probably don't need to make the start button hold-able/turbo-able :P

**Comment by littleguy77** [comment]
Let's continue this discussion on the version 3.0 brainstorming thread:
http://www.paulscode.com/forum/index.php?topic=1130.0

**Comment by BonzaiThePenguin** [comment]
I wasn't interested in Turbo myself either until I got to Canary Mary in Cloud Cuckooland in Banjo-Tooie. :P

Anyway, I agree that it's very low priority, so I won't bother bringing it up unless I end up really wanting it again in the future.
