### ISSUE TITLE
Does importing zip files actually work?

### ISSUE THREAD

**Issue by BonzaiThePenguin** [mupen64plus-ae/mupen64plus-ae#421]
So I was just playing around with zipped ROMs to make sure it "still" worked after the latest changes, but discovered that apparently it hasn't worked across any version I've tried? Is this affecting other people too? I don't want to start messing around with the code if it turns out I just have something set up wrong with my folder structure.

**Comment by littleguy77** [comment]
That's strange.  The version on master works really efficiently and effectively on all my devices, and I haven't heard any complaints from testers.  On my 2012 Nexus 7 it chews through massive OBB files really quickly (e.g. ones from third party apps that obviously don't have any N64 ROMs in them).  Based on my own experience, I'm thinking that folder-specific zip support might be more complexity that it's worth.

**Comment by BonzaiThePenguin** [comment]
It's more obvious if you put in an external SD card and tell it to find your ROMs somewhere on the entire thing (which is the default option on master). The getAllFiles function creates a new List for every folder, adds every File object to them, adds every List to each other, then iterates over these potentially millions of objects to find the 20 or so actual ROM files.

All I did was change it to check for ROM files *before* adding files to the list, and pass in the list as a parameter to add the files directly instead of instantiating new List and appending those. :P

If I had the motivation I would actually have ripped all of it out in favor of an indexed search (using the system's file indexer rather than a folder hierarchy traversal), *and* removed every MD5 calculation except when submitting a bug report (the only time a 100% strict match seems to be needed), due to how much the full file hash slows down common operations in the app. Me needs some speeds.

**Comment by BonzaiThePenguin** [comment]
I can revert the "search zips" thing to the older and simpler design if needed. I only made it per-folder to match the way it worked on the master branch. Don't actually use the feature myself.

**Comment by littleguy77** [comment]
Ok, thanks.  I just need to play "catch up" with what you've done.  I just don't want you to sink too much time into it before I've had a chance to see it and give thoughtful comments.

BTW the MD5's are central to the whole game-centric settings approach in V3.  Game-specific settings are associated with the unique MD5 fingerprint of the ROM.  V2 didn't persist much game-specific stuff, but when it did it just used the ROM filename, which causes all sorts of issues since it is mutable.  The plan is also to eventually have a database of game-specific defaults (e.g. use rice-fast as the default for some games, and touchscreen-digital or touchscreen-all for some games).  That database would have to be keyed off an immutable fingerprint of the ROM.  As I mentioned before, the CRC in the header is not sufficiently unique, so that is why the front-end and the upstream core both use MD5s.

**Comment by BonzaiThePenguin** [comment]
I get that, but would ROM hacks really need separate config options from the main ROM? Or even different official versions of a ROM? Especially when there are always new ROM hacks coming out (while the .ini is mostly designed for the N64's fixed library), and with a chance that the headers were altered slightly. In that situation it seems like *loose* matching would work better, with the super-strict matching coming into play when they go to complain about a crash and submit a report containing specific file offsets.

Anyway I mostly meant that the MD5 ends up being calculated in situations where it's already known, but isn't actually passed in to the function that need it. So like even though the MD5 is saved to the config file and stored within each GalleryItem, the other functions are only given a File object so they have to retrieve the ROM information by computing another hash and matching it against the ROM database again.

It's not a huge deal, of course (on my quad-core with a class-10 SD card it only takes a second or so), but... it could be better! Plus on older devices it's dog-slow, but then again *so would the N64 emulation* so who cares. Maybe if I had a slower SD card I would be more motivated. ;)

(Of course, full hashes are also useful for detecting duplicate files! Not sure if the app actually does this...)

**Comment by littleguy77** [comment]
Let me get through today's refactoring and then we can focus on design decisions.  For now I'm mostly talking out my butt since I'm still only have a high-level idea of what you've done so far.

BTW I pushed the appcompat and your changes to the drawables to master.  If your git-fu is strong, now would be an excellent time to rebase the New-Gallery-UI branch, ideally using `git rebase --interactive` and using the fixup feature.  If you're still new to git, then no worries.  There's definitely a big learning curve to the art of rebasing.

**Comment by BonzaiThePenguin** [comment]
My git-fu is weak. I usually "rebase" by downloading the ZIP and copying over changes manually.

**Comment by littleguy77** [comment]
Ok, no problem. I'll take care of the rebase and push it to a new branch.  I'll shoot for getting it done by the end of the day.  If you have any "fixups" to existing commits in the future, just mark them as "fixup commit xxxxx" in the commit message, and I'll re-insert them into the proper place during the rebase.
