### ISSUE TITLE
Report emulation issue with <game>

### ISSUE THREAD

**Issue by BonzaiThePenguin** [mupen64plus-ae/mupen64plus-ae#424]
I stubbed in a section in the sidebar for reporting emulation issues with the selected game. The idea is that this feature can automatically include the full ROM name, including the dump information, so we don't need to rely on the user's ability to include this information properly. GitHub lets you specify default subjects for new issues, so I figure I'll just route it there?

https://github.com/mupen64plus-ae/mupen64plus-ae/issues/new?title=Game%20name%20[M3]%20[!]

This would make the "Show full ROM names" option unnecessary, but I figure may as well include it since some people might like to see that information.

**Comment by littleguy77** [comment]
That would be very cool.  It would be nice if we just had one issue for each base name.  We could prepopulate the issue list using a script.  Then from the game, users would just be sent to the page, and they'd be able to tack on their comments (hopefully reading the ones there first).  We might be able to append their rip info to the message automatically.

We should definitely test this in a dummy repository first.  And ultimately I would vote to put these auto-issues into the (mupen64plus-ae-meta)[https://github.com/mupen64plus-ae/mupen64plus-ae-meta] repository (where the wiki is located) rather than this one.  Keep this one around for dev discussions and legacy issues.  Use the new one for more cohesive meta-info and issue tracking.

BTW if you have any scripts or whatever you used to scrape the ROM info, feel free to add it to the mupen64plus-ae-meta repository.

**Comment by BonzaiThePenguin** [comment]
> That would be very cool. It would be nice if we just had one issue for each base name. We could prepopulate the issue list using a script. Then from the game, users would just be sent to the page, and they'd be able to tack on their comments (hopefully reading the ones there first). We might be able to append their rip info to the message automatically.

That makes more sense. I was thinking maybe GitHub merges issues with the same name or something, but didn't actually check if that was the case.

> We should definitely test this in a dummy repository first. And ultimately I would vote to put these auto-issues into the mupen64plus-ae-meta repository (where the wiki is located) rather than this one. Keep this one around for dev discussions and legacy issues. Use the new one for more cohesive meta-info and issue tracking.

Also makes a lot of sense.

> BTW if you have any scripts or whatever you used to scrape the ROM info, feel free to add it to the mupen64plus-ae-meta repository.

The script is actually a very nastily-written (as I'm sure you can imagine) REALbasic project, and it required some non-trivial preprocessing of the data from Wikipedia. If it's important enough I can clean up the code and add a way to process the Wikipedia tables without preprocessing, but I don't think there's an easy way to handle some games being released under 4-5 different titles without manually looking it up and adding the alternate names.

**Comment by littleguy77** [comment]
> The script is actually a very nastily-written (as I'm sure you can imagine) REALbasic project, and it required some non-trivial preprocessing of the data from Wikipedia.

No worries, I was just throwing it out there
