### ISSUE TITLE
Cheats editor

### ISSUE THREAD

**Issue by BonzaiThePenguin** [mupen64plus-ae/mupen64plus-ae#425]
Just documenting the issues with the cheat system:
- the cheat names are hierarchical, but are presented in a flat list without any re-formatting. For this I was going to switch to hierarchical folders in the sidebar, where each "\" or "/" specifies a new folder. I figure the subtitle on the folders would be a simple `1/3 cheats enabled` so the user has some way of seeing which cheats are enabled without having to open any folders.
- some of the cheats in the file itself are wrong. I don't know how the licensing works (are we allowed to make arbitrary changes to the file contents?), but they can easily be repaired when loading them into the program. For example, the warp locations in the Japanese version of Banjo-Tooie accidentally have the last byte as part of the cheat name rather than the cheat code: `811217F0 ???? 0001:"42 Jinjo Village"`. There are also a ton of grammatical errors, misspellings, and formatting errors, which could really use some editing.
- the cheats are saved to the SharedPreferences, when it would work better to save it to the game's data folder in the mupen64plus database. If we were to change this, would we need to add support for loading from the SharedPreferences if data is already there? I figure the best option would be to copy the cheats from the cheat file to its own file in the game folder upon initialization, then the cheat editor would modify this local file directly. This would probably fix the long delays in loading the cheats too.

**Comment by BonzaiThePenguin** [comment]
https://github.com/mupen64plus-ae/mupen64plus-ae/issues/423

**Comment by littleguy77** [comment]
A hierarchical display would indeed be nice.

The cheats database is managed upstream (same directory as the ROMs database), so if you see typos, then please by all means submit a pull request there.

Just to clarify, the game-specific SharedPreferences store the flags which say which cheats are enabled.  Custom (user-created) cheats themselves are stored as a text file in the Profiles folder.  Moving all game-specific cheats info to a text file in the GameData directory would indeed be part of the larger migration to that approach as you bring up in #423.  We can handle that transformation all at once.

**Comment by BonzaiThePenguin** [comment]
> A hierarchical display would indeed be nice.

It's implemented now. Editing and enabling/disabling isn't implemented yet, but you can browse through the cheats at least. Much, *much* nicer than a flat list.

> The cheats database is managed upstream (same directory as the ROMs database), so if you see typos, then please by all means submit a pull request there.

Well, upstream in this case would be the Project 64 repo, wouldn't it? The header on the file says it's only allowed to be used with Project 64 version 1.7, but presumably Mupen licensed it under the GPL. Don't changes need to be submitted back to Project 64 as part of the licensing?

> Just to clarify, the game-specific SharedPreferences store the flags which say which cheats are enabled. Custom (user-created) cheats themselves are stored as a text file in the Profiles folder.

Oh, I didn't actually look that closely at that section of the code, heh.

**Comment by littleguy77** [comment]
Project64 is an entirely different and unrelated project.  The only relation is that we both use the same data since we both emulate the same system.  Project64 may have been the original source of the cheats data (I'm sure the licenses were checked long ago) but mupen64plus has been curating the version we use for a long time, for its own purposes.

- [mupen64plus](https://github.com/mupen64plus) is the "upstream" project, maintained by richard42 and several other devs.
- [mupen64plus-ae](https://github.com/mupen64plus-ae) is one of many "downstream" projects, maintained by paulscode and myself for the most part.

mupen64plus consists entirely of C/C++ code and is not intended to provide any fancy UI, though it does provide a reference console-based implementation that we layer on top of.  mupen64plus-ae consists mostly of Java (Android SDK in particular), with some C/C++/JNI stuff to bridge the gap.

The following upstream modules are copied *verbatim* into `mupen64plus-ae/jni/` using  `mupen64plus-ae/tools/pull-upstream`:
 - mupen64plus-audio-sdl 
 - mupen64plus-core
 - mupen64plus-rsp-hle
 - mupen64plus-ui-console
 - mupen64plus-video-glide64mk2
 - mupen64plus-video-rice

The synchronization is invoked manually but the git pull/copy mechanics are automated by script.  Downstream (mupen64plus-ae) maintains the following native code
 - ae-bridge (mostly JNI glue)
 - mupen64plus-input-android (custom input plugin for android)
 - mupen64plus-video-gln64 (unofficial video plugin not maintained upstream)
 - xperia-touchpad (obtains analog touch data from the Xperia Play device)

Downstream also contains copies of SDL2 (version 2.0.0-release), libpng, and libsamplerate.

**Comment by fzurita** [comment]
Cleaning up all issues.
