### ISSUE TITLE
KeyEvent + Dialog/Activity Switching Issue

### ISSUE THREAD

**Issue by xperia64** [mupen64plus-ae/mupen64plus-ae#435]
Lordus pointed out an issue he was having with DraStic&KeyEvents and I found that Mupen exhibits the same problem.
With a physical controller, hold some direction on the D-Pad in game, open a dialog (Game Speed for example), release the D-Pad, and close the dialog. The app will believe the D-Pad is still held until the D-Pad is pressed again OR an analog input event is received e.g. from joysticks or triggers. Digital input events will not "unpress" the D-Pad. A mouse event doesn't appear to release it either.
According to Lordus, this problem also happens if the app switches to another activity.

A couple of test cases from Lordus:
http://pastebin.com/ePZ5MeZ0
http://pastebin.com/MGjkFYjf

**Comment by littleguy77** [comment]
So the key up event is never being handled.  I guess that's not surprising.

Actually, the case you mention is the MotionEvent, since it involves a D-pad of the AXIS_HAT_X/Y variety.  That's why an analog input clears the issue.  On some controllers the D-pad produces KeyEvents, in which case pressing a digital input would clear the issue rather than analog.

But in any case, this doesn't seem surprising, and it seems a bit of a corner case that normally wouldn't occur.  Is there a particular use case where this actually happens?

**Comment by fzurita** [comment]
Won't fix
