### ISSUE TITLE
Core dead lock

### ISSUE THREAD

**Issue by fzurita** [mupen64plus-ae/mupen64plus-ae#514]
Very rarely, with the SLES audio plugin. The core can deadlock in the SLES audio plugin itself.

The deadlock happens at the method:

```EXPORT void CALL AiLenChanged(void)```

at this location:

```
pthread_mutex_lock(&(lock.mutex);
```

in main.c of the SLES audio plugin

**Comment by Gillou68310** [comment]
Thanks for reporting this issue.
The deadlock actually happens on ```pthread_cond_timedwait()``` I already spend a few hours trying to fix it, without success.

The only solution I end up thinking of is to use ```pthread_cond_timedwait()``` with a configurable timeout, the problem is that the emulation will be freezed until the timeout is over if the deadlock happens.

@paulscode maybe you have an idea of what's going on here ;-)

@fzurita In the meantime I suggest we put back the SDL plugin as the default audio plugin and 2048 as the default buffer size.

**Comment by fzurita** [comment]
Changing the plugin may not be necessary. It doesn't happen that often and when it does happen, the user is able to quit out of the app and start over.

I'll take a look at this as well, maybe I can find where the issue is.

**Comment by fzurita** [comment]
I've been looking at this. It almost seems like ```queueCallback``` is never getting called. I wonder if updating SLES to API level 15 would fix this. Right now we are using API level 9.

**Comment by fzurita** [comment]
I think I see an issue, the ```threadLock lock``` structure needs to be ```volatile```.

**Comment by fzurita** [comment]
i think we are giving this call an invalid set of parameters.

```
        (*bufferQueue)->Enqueue(bufferQueue, secondaryBuffers[secondaryBufferIndex], secondaryBufferBytes);
```
And the callback is not happening because of that.

We really should check the return value of that call, and if it fails, increment ```lock.value```.

**Comment by fzurita** [comment]
This can no longer happen under the new threaded SLES audio.

https://github.com/mupen64plus-ae/mupen64plus-ae/pull/546
