### ISSUE TITLE
When the sidebar is closed from software the menu/arrow animation in the toolbar isn't updated

### ISSUE THREAD

**Issue by Gillou68310** [mupen64plus-ae/mupen64plus-ae#580]

**Comment by fzurita** [comment]
Hmmm.... this one is a tough one. I can't get the arrow to turn to a "hamburger" no matter what I do. If I close the drawer normally, it turns correctly, but then the animation is shown.

**Comment by fzurita** [comment]
Actually, I found a way, but it requires updating the support library again.

We really need to move to Android Studio. With android studio, you don't have to include the support libraries as part of your project, they are included automatically but changing the gradle config. I already have a gradle configuration for Android Studio under the tools directory of the project.

**Comment by Gillou68310** [comment]
Is that really bad to include the support libraries as part of the project? It would be cool if we can keep eclipse compatibility.

**Comment by fzurita** [comment]
The new support libraries are not compatible with eclipse by default. So you have to find someone who has converted them into eclipse projects and use that instead.

**Comment by Gillou68310** [comment]
Oh I see.

**Comment by Gillou68310** [comment]
Were can I find the new library, I'll try to take a look at it.

**Comment by fzurita** [comment]
It's just cumbersome. With Android Studio, it so easy, it's just a change to the build.gradle file. Plus, with Android Studio you get to use the newest Java version.

**Comment by fzurita** [comment]
Here is where I got them last time I updated them:

https://github.com/dandar3

**Comment by Gillou68310** [comment]
Well I guess we'll have to drop eclipse compatibility then :-(
I'd like try Android Studio before giving my final answer.

**Comment by Gillou68310** [comment]
1.6Gb wooooow

**Comment by fzurita** [comment]
Yeah, it's not too bad.

**Comment by fzurita** [comment]
NDK compatibility is not that great yet, but it will improve in Android Studio v2.2, which is the next version.

**Comment by fzurita** [comment]
I typed up some instructions here for setting up Android Studio 2.1 with our project:

https://github.com/mupen64plus-ae/mupen64plus-ae/issues/566

And 1.2 GB is nothing. You are going to have to download the latest SDK/NDK from Android Studio.

**Comment by Gillou68310** [comment]
I downloaded the standalone android-studio version with no sdk. I already have sdk+ndk for eclipse.

**Comment by fzurita** [comment]
Gotcha

**Comment by Gillou68310** [comment]
Sorry but I don't understand the instructions could explain again step by step.

**Comment by fzurita** [comment]
I can come up with a very specific set of instructions that say step by step what to click and what commands to type, but it will have to wait until I'm home, since I'm at work right now. 

At a very high level, this are what the instructions are:

1. Create a new Android Studio project, I think by default this creates a mobile and TV "modules"
2. Navigate to mobile/src.
3. Create a directory called "main" under mobile/src
4. Checkout the project to this main directory. So the main directory should contains all of our top level directories.
5. Under the tools directory of our directory structure, you will find a android-studio directory. In there, there are two files, ```build.gradle``` and ```mobile/build.gradle```. ```build.gradle``` goes at the very top level of the android studio project, it should replace the ```build.gradle``` file already present there. ```mobile/build.gradle``` replace the ```build.gradle``` under the mobile module.

The one bad thing about Android Studio is that our project directory structure is not ideally setup for it, so I had to do a couple of workarounds in the build.gradle files. If we decide to drop Eclipse support completely, I would like to modify our directory structure so that it matches the requirements of Android Studio better.

**Comment by Gillou68310** [comment]
Why is there a NDK_DEBUG=1 in the task ndkBuild in the gradle file?

**Comment by fzurita** [comment]
Hmm.... that's probably not needed. I can't remember why I put that there.

**Comment by fzurita** [comment]
I just pushed an update to the gradle files.

**Comment by Gillou68310** [comment]
NDK_DEBUG=1 is the equivalent of APP_OPTIM=debug but since APP_OPTIM=release in Application.mk I'm not sure which one has the priority.

**Comment by Gillou68310** [comment]
Ok sorry but I'm really not comfortable with android studio. I'm not a fan of eclipse either but I guess I get used to it over years.
I tried updating the android support library for the eclipse project https://github.com/Gillou68310/mupen64plus-ae/tree/android_support_v24_2_0 unfortunately it's crashing when ````super.onCreate( savedInstanceState );```` is called in SplashActivity.
I guess you don't have this issue with android studio?

**Comment by fzurita** [comment]
No

**Comment by fzurita** [comment]
Ok, here you go. Official support for Eclipse was dropped:

https://developer.android.com/studio/tools/sdk/eclipse-adt.html

It hasn't been supported for a while now.

**Comment by Gillou68310** [comment]
Well if that's what google wants I guess I can't fight.
Could you provide a branch with the project migrated to android studio (new folder structure + eclipse free) ?

**Comment by fzurita** [comment]
Yeah, I think I can.

**Comment by Gillou68310** [comment]
Yeah that was a rhetorical question of course ;-)

**Comment by fzurita** [comment]
Ok, I went ahead and did a full migrate to Android Studio. Here is the branch:

https://github.com/mupen64plus-ae/mupen64plus-ae/tree/android_studio

Unfortunately, due to the renamed files, you have to use this command to look at history for files that were renamed:

```git log --follow```

If you want to look at history from github, you have to pick a commit before the rename, and look at history from there.

**Comment by fzurita** [comment]
You should be able to pull this branch import it directly into android studio.

To run, look at the top green "Play" button.

**Comment by Gillou68310** [comment]
Is the gradle.properties file necessary? I had to change the -Xmx2048m option to -Xmx1024m in order to make it work on my computer. 
Also the lib folder is missing from jni\android_framework and jni\GLES3
Everything else looks good nice job ;-)

**Comment by fzurita** [comment]
Hmm, I wonder why git deleted then, I can add them back.

I can try deleting the gradle.properties file and checking if it get regenerated. If it does, I can add it to the ignore list.

Other than those few things, do you think it's ready? I can create a branch called pre_android_studio to keep the old history easily accessible.

**Comment by Gillou68310** [comment]
> Other than those few things, do you think we are ready? I can create a branch called pre_android_studio to keep the old history easily accessible.

Don't forget to update the scripts other than that yeah I think we are ready. You can create a tag rather than a branch for the pre_android_studio.

**Comment by fzurita** [comment]
Ok, good idea.

**Comment by fzurita** [comment]
ok, I updated it, The gradle.properties is not necessary. It doesn't seem to get generated if it's not there either.

I'll do one more commit later to update the tools directory, rebase with master, and the merge to the master branch.
