### ISSUE TITLE
Add more rendering resolutions

### ISSUE THREAD

**Issue by xperia64** [mupen64plus-ae/mupen64plus-ae#582]
More resolutions should be added to the Rendering Resolution setting, preferably automatic multiples of 320x240. If I want to run Mupen @1080p on a 4k device, I currently can't.

**Comment by fzurita** [comment]
Yeah, out should be easy to add more, you should take on the task!

**Comment by retrobenny** [comment]
@fzurita 

Since this counts and the same thing I am talking about despite being from over 2 years ago...

Native doesn't work for making it use 4K,it gets slammed by the bad DPI values causing it to always be the non-wide 1080P resolution instead of honoring 4K properly because I changed the value manually then tried running the game,only for it to revert to 1440 x 1080 on the game specific cfg that I modified.
Meanwhile RetroArch lets you pick insane resolutions at and slightly beyond 4K on its Dolphin core as well as stand-alone Dolphin on Android because it can be selected in the list instead of being an auto setting.
Adding options for directly selecting 1080P and 2160P may likely fix this limitation problem instead of relying on often-times unreliable/restrictive automation.
The DPI issue causes scale annoyances globally on many other apps in Shield TV as well,making them assume 1080P is the Native resolution even though I have 2160P 60hz applied.

If it is indeed running at 4K,then I also lack the option to make it use 1080P while my device is in 4K resolution mode.
Having manual options for both of those resolutions would allow more direct access to resolution choice.

**Comment by fzurita** [comment]
I added these resolutions:

        5760x4320
        2880x2160
        1440x1080
Any more do you think I should add?

**Comment by fzurita** [comment]
bbf208dd79d9e5add979307b3877c98a93b216f2

**Comment by retrobenny** [comment]
Rice is a MVP because it can run in the 8K resolution mode quite well but GLideN64 chews through performance with slowdown on 4K and downright sluggish with 8K scale (on 4K resolution).
This extra impact will be useful for future testing of GLideN64 updates if any further attempts at performance boosts are made and if other certain recompiler things get done to attempt performance increases there.

**Comment by fzurita** [comment]
Cool, I ended up two more resolutions since some people requested.
