### ISSUE TITLE
OnePlus3 FPS Dropped, 

### ISSUE THREAD

**Issue by anarchyguitarist** [mupen64plus-ae/mupen64plus-ae#586]
After I update the application 3.0.12 found 2 bugs that possible exist for many devices and not only OP3
FPS start to dropped on Legend of Zelda Majoras Mask when I try to use bubbles, 
Glide64 accurate/fast plugin only, 
Rice plugin runs smooth but have glitches cause is on beta. 
Plus after I figure out that bug I test few other games and is unplayable now something change on GlideN64-GLES when game use effects like shadows  FPS dropped  to 5-3.

Plus my device use opengl 3.1 can't use the opengl3.1 plugin, some games are on empty blank  some others have polygons and glitches unplayable, probably my device is not assigned to glide64 opengl3.1
Before the update my device was running smooth with Glide64.

**Comment by fzurita** [comment]
Ok, thanks for reporting these issues, but it probably won't do much good to create issues for that here since this app is mostly a front end and we pull everything from the corresponding projects.

These seem to be issues related to specific video plugins. I would create issues in the corresponding projects, also, I would try to create one issue per problem you are having instead of putting many problems in one issue.

Here is the Glide64 project:
https://github.com/mupen64plus/mupen64plus-video-glide64mk2

Here is the GLideN64 project:
https://github.com/gonetz/GLideN64

It really sounds like the plugins just need to be more optimized.

**Comment by anarchyguitarist** [comment]
Thanks for response I do the same.

**Comment by fzurita** [comment]
If you write issues, make sure you mention you are using them in a mobile device.

**Comment by fzurita** [comment]
Has performance and graphical glitches improved in the last few versions?

**Comment by anarchyguitarist** [comment]
Everything fixed with new update, no more glitches, running smooth always
with high stable frame rate, opengl 3.1 supported now. Great work.
