### ISSUE TITLE
Paper mario 64 

### ISSUE THREAD

**Issue by starkenzo** [mupen64plus-ae/mupen64plus-ae#607]
Some of the text that characters say does not appears in the game, like the "stars" characters when they same something in the game, it just appears blank, so I can't read it, and in this game is very important to know what they have to say tp you in order to pass the game.

**Comment by fzurita** [comment]
Hello, you can use GLideN64-GLES-X.X emulation profile to fix the text.

Also, this is a problem of the Glide64 video plugin, not mupen64plus-ae/FZ which is just a front end. 
Please create an issue right here: https://github.com/mupen64plus/mupen64plus-video-glide64mk2

The problem is that Glide64 lacks noise emulation I believe.
