### ISSUE TITLE
Paper mario emulation bugs - star spirit words and start button freezes

### ISSUE THREAD

**Issue by Deniedpluto** [mupen64plus-ae/mupen64plus-ae#609]
The First Is An issue with the star spirit speech bubbles which appear blank.  The other is when I press the start button the game freezes and crashes. 

I am playing on a Samsung Galaxy Note 4.

**Comment by fzurita** [comment]
Yeah, I'm aware of these issues. Paper Mario doesn't work well with save states. So to avoid freezes when pressing the start button, don't use save states.

The issue with the star spirit speech bubbles is because Glide64 is missing noise emulation I believe. To avoid that issue, switch to the GLideN64-GLES-X.X emulation profiles.

**Comment by fzurita** [comment]
Here is the core issue about paper Mario pausing:
https://github.com/mupen64plus/mupen64plus-core/issues/197

**Comment by fzurita** [comment]
Here is the issue in Glide64:
https://github.com/mupen64plus/mupen64plus-video-glide64mk2/issues/77
