### ISSUE TITLE
How to load .zip faster?

### ISSUE THREAD

**Issue by theShrike760** [mupen64plus-ae/mupen64plus-ae#627]
Afternoon Francisco,

I apologize for creating a bug to ask you a few questions but I couldn't figure out any way to msg you on here or send you an email. My questions are as follows:

1) Is there a way to keep the emulator from having to reload all high res textures each time you reload the same game? I have a large pack for OOT and it is around 900mb. It takes FOREVER to load all those files each time i try and start the game.

2) Do you know how to convert a .zip collection of files into a .htc?  The .htc high res texture pack i have installs much faster on each boot of a game. I have been unable to find any information on what exactly a .htc is or what the directory structure and file types need to be. 

Thanks,
Chris

**Comment by theShrike760** [comment]
Forgot to add. Also had some crashes when trying to load such a large texture pack.

**Comment by fzurita** [comment]
Texture packs are automatically converted to HTC format by GLideN64 when the ROM is closed. So GLideN64 will cache them.

Unfortunately, I broke the caching mechanism in the last update. I will fix it within the next couple of days. I just need to figure out a way to deal with the situation.

My email is fzurita@gmail.com.

**Comment by theShrike760** [comment]
Can you elaborate on which portion of my question above this covers? By fixing it will it keep it from crashing on me? Will it fix the slow reload times? Something else? 

Thanks!

**Comment by fzurita** [comment]
Caching will fix the slow reload times.

It will not fix the crashing. Crashing is due to memory utilization. GLideN64 is coded in a way that makes it need the whole texture pack loaded in memory. The Zelda texture pack is really big and Android doesn't like it when a process takes too much memory, which causes the crash.

There is no way that I know off to manually convert the texture pack to HTC in Android. I guess you could load the texture pack in a PC and then let the PC so the conversion. Then you would have to copy only the HTC file to your phone.

**Comment by fzurita** [comment]
@theShrike760 If you download the latest or build the latest. The caching of textures should be fix. Let me know if it's not.

**Comment by theShrike760** [comment]
@fzurita Tried the latest and get this build error:
Error:A problem occurred configuring project ':app'.
> executing external native build for ndkBuild /Users/chrislansman/Downloads/mupen64plus-ae-master 2/app/src/main/jni/Android.mk
