### ISSUE TITLE
SDL audio plugin

### ISSUE THREAD

**Issue by ZacharyFoxx** [mupen64plus-ae/mupen64plus-ae#692]
Hi,
Is it possible bring back the SDL audio plugin? The performance using this plugins is better than with SLES. I tried GoldenEye, Pilotwings and Cruis'n USA and the performance was better with SDL audio plugin. I used the version 121 comparing with the last version in the play store, 183.

**Comment by fzurita** [comment]
There should be zero performance difference. In fact it should be faster since it doesn't have to go through the SDL layer.

Try this, go to settings then audio and disable "Synchronize audio and video". Also, try setting the sampling rate to "best for hardware" and enable "Floating point samples".

What device do you have?

**Comment by fzurita** [comment]
Also, try disabling audio time stretching.
