### ISSUE TITLE
Ads on clones

### ISSUE THREAD

**Issue by marcklinker** [mupen64plus-ae/mupen64plus-ae#721]
I tried downloading a N64 emulator to my phone yesterday. I originally downloaded MegaN64, because that ranks first, but the app had graphical issues with some of my games. Then I downloaded Mupen64Plus FZ & Retro N64, both worked, but Retro N64 has ads (spam clone maybe?)

There seems to be a problem with ad infested clones on Google Play. Does the community see this as an issue? Can we get these taken down?

**Comment by fzurita** [comment]
Yes, the community does see this as an issue. It's a constant battle. Because the project is open source, the second a clone gets taken down, another takes its place.

In the end, I only report the ones that have embedded illegal ROM download links or that include malware. I don't think there is much we can do about it though since Google is not very cooperative.

**Comment by fzurita** [comment]
Also, Mupen64Plus FZ is the one I package and put on the play store, the only differences is a "rate me" popup and an option to tip me personally.

You can also download one from F-droid that has almost zero modifications except for the removal of some proprietary libraries.
