### ISSUE TITLE
L+R buttons not registering in controller profile

### ISSUE THREAD

**Issue by smurkcs** [mupen64plus-ae/mupen64plus-ae#754]
I'm having an issue where my controller profile will not register the L or R button presses no matter what i try... the interesting thing is, the app is registering the button presses just fine in the Controller Diagnostics as Motion Events. 
AXIS_LTRIGGER (gamepad) +0.00 - +1.00  
AXIS_RTRIGGER (gamepad) +0.00 - +1.00

It seems like the controller profile config just doesn't want to see them as valid? I'm at a loss here. Btw this is on a chromebook running mupen64plus FZ 3.0.222

**Comment by fzurita** [comment]
Just getting to this, which controller do you have?

**Comment by smurkcs** [comment]
I've tried stock N64 controllers and a brand new pair of non-nintendo N64 controllers, running through a Mayfair USB adapter. Bought a second Mayfair to make sure it wasn't that component, but the problem still persists.

Thanks for getting back to me! :)

**Comment by fzurita** [comment]
Chromebooks must be doing something weird since this works fine in Android.

**Comment by i-bruh** [comment]
what mayflash u have?

**Comment by fzurita** [comment]
I ended up trying a chromebook with a PS4 controller and everything worked great. So the problem is probably not the app at this time. I would attempt to download any joystick tester application from the google play store and see if the L and R buttons work correctly there with the adapter. If they don't, then there is nothing that the app can do about it,
