### ISSUE TITLE
Cant restart file after beating game 

### ISSUE THREAD

**Issue by milesarose** [mupen64plus-ae/mupen64plus-ae#836]
Beat the game. Credits went all the way to the end. Stopped at very last cutscence and now stuck. Cant restart erase or begin new file. Paid for premium service and still didnt help. Looking for customer service number so I can get a refund. Highly disappointing.

**Comment by fzurita** [comment]
Hello, first of all, are you using M64Plus FZ from the Google play store? If so, you can use the "start" option instead of the "resume" option.

The start option will continue from the last time you saved in game. 

If you would like a refund on the app, and the app that you bought is M64Plus FZ (there are a lot of clones), then I can give you a refund if you provide your email address.
