### ISSUE TITLE
Netplay desync

### ISSUE THREAD

**Issue by RockinRay3305** [mupen64plus-ae/mupen64plus-ae#891]
So I tested out the new netplay feature on my phone and chromebook. And I decided to play Mario Party 2 and got the minigame Bumper Balls. My laptop lagged and on my phone Wario won but on my laptop he fell. Both of my devices were then playing completely different perspectives of Mario Party 2.

**Comment by fzurita** [comment]
Yeah, it's a known issue. You should had gotten a netplay has desynced error message. The reason that happened is because the chromebook has a x86 based processor while a phone has a arm based processor. Because they execute instructions slightly different, desyncs will happen.

Only way to keep that from happening is to switch the R4300 emulator from dynarec to cached interpreter or have matching CPU architectures.

**Comment by RockinRay3305** [comment]
Oh ok makes sense thanks for clearing that up.

**Comment by David60pro** [comment]
Cómo se hace eso
